languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Ty Williams"
 copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "Welcome to my website"

[params.author]
   name = "Ty Williams"
   # image = "img/me.png"
   image = "img/profile.webp"
   headline = "Data-Driven Problem Solver "
   #bio = "To be completed..."
   links = [

     { github = "https://github.com/tywilliamsca" },
     { email = "mailto:admin@tywilliams.ca" },

     { linkedin = "https://linkedin.com/in/tywilliamsca" },

     { x-twitter = "https://twitter.com/tywilliamsca" },

   ]
